export const GET_SERVERS_STATE = 'GET_SERVERS_STATE';
export const SET_SERVERS_START = 'SET_SERVERS_START';
export const SET_SERVERS_FINISH = 'SET_SERVERS_FINISH';
export const SET_SERVER_START = 'SET_SERVER_START';
export const SET_SERVER_FINISH = 'SET_SERVER_FINISH';
export const GET_SERVER_ERROR = 'GET_SERVER_ERROR';
