version: '3.3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile-js
    environment:
      - BACKEND_URL=http://web
    volumes:
      - './website/spa:/app'
      - '/app/node_modules'
    ports:
      - 80:5000

  web:
    image: 'nginx:latest'
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./website/api:/api
    ports:
      - 8080:80
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./website/api:/api
    environment:
      - MYSQL_HOST={host}
      - MYSQL_ROOT_PASSWORD=${password}
      - MYSQL_DATABASE=${db}
    depends_on:
      - 'mysql'

  mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=${password}
      - MYSQL_DATABASE=${db}
    volumes:
      - ./sql_data:/var/lib/mysql

